// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// SplineBlendAll
NumericVector SplineBlendAll(NumericVector z, NumericVector knots, int splineOrder, int nBins);
RcppExport SEXP BSplineMI_SplineBlendAll(SEXP zSEXP, SEXP knotsSEXP, SEXP splineOrderSEXP, SEXP nBinsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type knots(knotsSEXP);
    Rcpp::traits::input_parameter< int >::type splineOrder(splineOrderSEXP);
    Rcpp::traits::input_parameter< int >::type nBins(nBinsSEXP);
    rcpp_result_gen = Rcpp::wrap(SplineBlendAll(z, knots, splineOrder, nBins));
    return rcpp_result_gen;
END_RCPP
}
// hist2d_C
NumericVector hist2d_C(NumericVector weights, int i1, int i2);
RcppExport SEXP BSplineMI_hist2d_C(SEXP weightsSEXP, SEXP i1SEXP, SEXP i2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type i1(i1SEXP);
    Rcpp::traits::input_parameter< int >::type i2(i2SEXP);
    rcpp_result_gen = Rcpp::wrap(hist2d_C(weights, i1, i2));
    return rcpp_result_gen;
END_RCPP
}
// entropy2d_C
double entropy2d_C(NumericVector weights, int i1, int i2);
RcppExport SEXP BSplineMI_entropy2d_C(SEXP weightsSEXP, SEXP i1SEXP, SEXP i2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type i1(i1SEXP);
    Rcpp::traits::input_parameter< int >::type i2(i2SEXP);
    rcpp_result_gen = Rcpp::wrap(entropy2d_C(weights, i1, i2));
    return rcpp_result_gen;
END_RCPP
}
